#!/usr/bin/env python3
"""
Scrape the public Mobalytics Ironclad guide and export lightweight build data.

Run:
    python scripts/scrape_mobalytics_ironclad_builds.py

Output:
    data/build_guides/ironclad/mobalytics_builds.json
    data/build_guides/ironclad/mobalytics_builds.md
"""
from __future__ import annotations

import html as html_lib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

URL = "https://mobalytics.gg/slay-the-spire-2/characters/ironclad-guide#buildsdecks-1"
OUT_DIR = Path(__file__).resolve().parent.parent / "data" / "build_guides" / "ironclad"

_CARD_SPLIT = re.compile(r"\s+[–-]\s+")


def fetch_html(url: str) -> str:
    req = Request(url, headers={"User-Agent": "Mozilla/5.0 BoberInSpire-mobalytics-scraper/1.0"})
    with urlopen(req, timeout=90) as resp:
        return resp.read().decode("utf-8", errors="replace")


def _strip_tags(text: str) -> str:
    t = re.sub(r"<[^>]+>", "", text)
    t = html_lib.unescape(t)
    t = re.sub(r"\s+", " ", t)
    return t.strip()


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")


def _extract_li_names(chunk: str) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for m in re.finditer(r"<li[^>]*>(.*?)</li>", chunk, re.DOTALL | re.IGNORECASE):
        txt = _strip_tags(m.group(1))
        if not txt:
            continue
        card = _CARD_SPLIT.split(txt, maxsplit=1)[0].strip()
        if card == txt:
            # Fallback for prose bullets like:
            # "Thrash hits multiple times..." -> "Thrash"
            lead = re.match(r"^([A-Z][A-Za-z'!?,]+(?:\s+[A-Z][A-Za-z'!?,]+){0,4})\b", txt)
            if lead:
                card = lead.group(1).strip().rstrip(".,:;")
        if not card:
            continue
        key = card.lower()
        if key not in seen:
            seen.add(key)
            out.append(card)
    return out


def _section_after_heading(chunk: str, heading: str) -> str:
    # Heading text is often wrapped in nested spans inside h3.
    m = re.search(
        rf"<h3[^>]*>.*?{re.escape(heading)}.*?</h3>",
        chunk,
        re.IGNORECASE | re.DOTALL,
    )
    if not m:
        return ""
    start = m.end()
    nxt = re.search(r"<h[23][^>]*>", chunk[start:], re.IGNORECASE)
    end = start + nxt.start() if nxt else len(chunk)
    return chunk[start:end]


def parse_builds(html: str) -> list[dict]:
    sec_start = html.lower().find("builds/decks")
    if sec_start < 0:
        sec_start = 0
    work = html[sec_start:]

    h2s = list(
        re.finditer(r"<h2[^>]*>\s*([^<]*(?:Build|Deck))\s*</h2>", work, re.IGNORECASE)
    )
    builds: list[dict] = []
    for i, hm in enumerate(h2s):
        title = _strip_tags(hm.group(1))
        if not title:
            continue
        start = hm.end()
        end = h2s[i + 1].start() if i + 1 < len(h2s) else len(work)
        block = work[start:end]

        key_cards = _extract_li_names(_section_after_heading(block, "Key Cards"))
        relic_chunk = _section_after_heading(block, "Relics")
        if not relic_chunk:
            relic_chunk = _section_after_heading(block, "Defining Relics")
        relics = _extract_li_names(relic_chunk)
        tips_txt = _section_after_heading(block, "Tips")
        tips = _extract_li_names(tips_txt)

        if not key_cards and not relics:
            # Skip non-build sections accidentally captured.
            continue

        builds.append(
            {
                "id": _slugify(title),
                "url": URL,
                "title": title,
                "build_tier": "",
                "description": "",
                "core_cards": [{"name": c, "slug": ""} for c in key_cards],
                "card_acquisition_priority": [],
                "flex_cards": [],
                "relic_priority": {
                    "best": [{"name": r, "note": ""} for r in relics],
                    "good": [],
                    "avoid": [],
                },
                "key_relics_sidebar": [],
                "tips": tips,
            }
        )
    return builds


def write_md(payload: dict) -> str:
    lines = [
        "# Ironclad builds — Mobalytics",
        "",
        f"> Source: {payload['source']}",
        f"> Generated: {payload['generated_at']}",
        "",
        "Generated by `scripts/scrape_mobalytics_ironclad_builds.py`.",
        "",
    ]
    for b in payload.get("builds", []):
        lines.append(f"## {b.get('title', 'Build')}")
        lines.append("")
        if b.get("core_cards"):
            lines.append("### Key cards")
            lines.append("")
            for c in b["core_cards"]:
                lines.append(f"- {c['name']}")
            lines.append("")
        best = ((b.get("relic_priority") or {}).get("best") or [])
        if best:
            lines.append("### Relics")
            lines.append("")
            for r in best:
                lines.append(f"- {r['name']}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    try:
        html = fetch_html(URL)
    except Exception as exc:
        print(f"Fetch failed: {exc}", file=sys.stderr)
        return 1

    builds = parse_builds(html)
    if not builds:
        print("Could not parse any Ironclad builds from Mobalytics HTML.", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    payload = {
        "source": URL,
        "character": "Ironclad",
        "generated_at": now,
        "note": "Generated from Mobalytics Ironclad guide. Parsing is best-effort because page HTML can change.",
        "builds": builds,
    }
    out_json = OUT_DIR / "mobalytics_builds.json"
    out_md = OUT_DIR / "mobalytics_builds.md"
    out_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    out_md.write_text(write_md(payload), encoding="utf-8")
    print(f"Wrote {out_json} ({len(builds)} builds)")
    print(f"Wrote {out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
