#!/usr/bin/env python3
"""
Best-effort refresh for Mobalytics STS2 card tiers.

Mobalytics often renders card-tier grids in dynamic client-side structures, so this script:
  1) fetches the live page,
  2) tries to parse embedded tier JSON blocks when available,
  3) falls back to keeping the existing file unchanged if extraction is not reliable.

Run:
    python scripts/scrape_mobalytics_tiers.py
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

URL = "https://mobalytics.gg/slay-the-spire-2/tier-lists/cards"
OUT = Path(__file__).resolve().parent.parent / "data" / "tier_lists" / "mobalytics_cards.json"
CHARS = ("Ironclad", "Silent", "Defect", "Regent", "Necrobinder")
TIERS = ("S", "A", "B", "C", "D")


def fetch_html(url: str) -> str:
    req = Request(url, headers={"User-Agent": "Mozilla/5.0 BoberInSpire-mobalytics-tier-scraper/1.0"})
    with urlopen(req, timeout=90) as resp:
        return resp.read().decode("utf-8", errors="replace")


def _extract_object_fragment(html: str, key: str) -> str | None:
    """
    Find a JSON-like object fragment that starts at '"<key>": {' and ends at matching brace.
    """
    needle = f'"{key}"'
    start_key = html.find(needle)
    if start_key < 0:
        return None
    brace_start = html.find("{", start_key)
    if brace_start < 0:
        return None
    depth = 0
    i = brace_start
    while i < len(html):
        ch = html[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return html[brace_start : i + 1]
        i += 1
    return None


def _try_parse_embedded_tiers(html: str) -> dict[str, dict[str, list[str]]]:
    parsed: dict[str, dict[str, list[str]]] = {}
    for char in CHARS:
        frag = _extract_object_fragment(html, char)
        if not frag:
            continue
        # Try to capture tier arrays inside this character object.
        tiers: dict[str, list[str]] = {}
        for t in TIERS:
            m = re.search(rf'"{t}"\s*:\s*\[([^\]]*)\]', frag, re.DOTALL)
            if not m:
                continue
            names = [x.strip().strip('"') for x in m.group(1).split(",")]
            names = [n for n in names if n]
            if names:
                tiers[t] = names
        if tiers:
            parsed[char] = tiers
    return parsed


def _load_existing_payload() -> dict:
    if not OUT.is_file():
        return {"source": URL, "characters": {}}
    try:
        raw = json.loads(OUT.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"source": URL, "characters": {}}
    if not isinstance(raw, dict):
        return {"source": URL, "characters": {}}
    return raw


def main() -> int:
    try:
        html = fetch_html(URL)
    except Exception as exc:
        print(f"Fetch failed {URL}: {exc}", file=sys.stderr)
        return 1

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    existing = _load_existing_payload()
    extracted = _try_parse_embedded_tiers(html)
    total = sum(len(v) for c in extracted.values() for v in c.values())

    if total >= 100:
        payload = {
            "source": URL,
            "snapshot_date": now[:10],
            "checked_at": now,
            "note": "Generated by scripts/scrape_mobalytics_tiers.py from embedded page data.",
            "characters": extracted,
        }
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"Wrote {OUT} ({len(extracted)} chars, {total} card placements)")
        return 0

    # Fallback: keep current manual snapshot, just report inability.
    existing["source"] = URL
    existing["checked_at"] = now
    existing["note"] = (
        "Live page fetched by scripts/scrape_mobalytics_tiers.py, but tier-card grids were "
        "not reliably extractable from server HTML. Kept existing curated snapshot."
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(existing, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("Warning: could not reliably extract card tiers from live HTML; kept existing snapshot.")
    print(f"Wrote {OUT} (fallback)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
