from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Sequence

from .card_effects import parse_card_effects
from .models import Card, Enemy, GameState, PlayerState, Relic


VULNERABLE_MULTIPLIER = 1.5
WEAK_DAMAGE_MULTIPLIER = 0.75
WEAK_BLOCK_REDUCTION = 0.75
MIN_ENERGY_FOR_SORT = 0.5


# ── Low-level card math ────────────────────────────────────────────────

@dataclass
class DamageResult:
    """Result of a single card being played against a single enemy."""
    card_name: str
    raw_damage: int
    final_damage: int
    hits: int
    total_damage: int
    energy_spent: int


@dataclass
class TurnResult:
    """Aggregated result for the whole turn against a target enemy."""
    enemy_name: str
    enemy_hp: int
    per_card: list[DamageResult] = field(default_factory=list)
    total_damage: int = 0
    total_block: int = 0
    energy_remaining: int = 0
    is_lethal: bool = False
    overkill: int = 0


def compute_card_damage(
    card: Card,
    strength: int,
    vigor: int,
    is_weak: bool,
    enemy_vulnerable: bool,
) -> int:
    """Return total damage one card deals (all hits) to one enemy."""
    if not card.is_attack:
        return 0

    base = card.damage + strength
    per_hit = base + vigor

    if is_weak:
        per_hit = math.floor(per_hit * WEAK_DAMAGE_MULTIPLIER)
    if enemy_vulnerable:
        per_hit = math.floor(per_hit * VULNERABLE_MULTIPLIER)

    return max(per_hit, 0) * max(card.hits, 1)


FRAIL_BLOCK_MULTIPLIER = 0.75


def compute_card_block(card: Card, dexterity: int, is_frail: bool = False) -> int:
    """Return block generated by one skill card. Frail reduces block by 25%."""
    if card.is_attack or card.block <= 0:
        return 0
    blk = card.block + dexterity
    if is_frail:
        blk = math.floor(blk * FRAIL_BLOCK_MULTIPLIER)
    return blk


# ── Incoming damage ───────────────────────────────────────────────────

@dataclass
class EnemyIncoming:
    name: str
    intended_damage: int
    intended_hits: int
    total_damage: int
    move_type: str


@dataclass
class IncomingDamageResult:
    """Breakdown of incoming enemy damage for the turn."""
    per_enemy: list[EnemyIncoming] = field(default_factory=list)
    total_incoming: int = 0
    player_block: int = 0
    net_damage: int = 0
    expected_hp: int = 0


def calculate_incoming_damage(state: GameState) -> IncomingDamageResult:
    """Calculate total damage enemies will deal and net HP loss after current block."""
    per_enemy: list[EnemyIncoming] = []
    total_incoming = 0

    for enemy in state.enemies:
        dmg = enemy.intended_damage
        per_enemy.append(EnemyIncoming(
            name=enemy.name,
            intended_damage=enemy.intended_damage,
            intended_hits=enemy.intended_hits,
            total_damage=dmg,
            move_type=enemy.intended_move,
        ))
        total_incoming += dmg

    player_block = state.player.block
    net_damage = max(total_incoming - player_block, 0)
    expected_hp = max(state.player.hp - net_damage, 0)

    return IncomingDamageResult(
        per_enemy=per_enemy,
        total_incoming=total_incoming,
        player_block=player_block,
        net_damage=net_damage,
        expected_hp=expected_hp,
    )


# ── Strategy solver ───────────────────────────────────────────────────

@dataclass
class CardSuggestion:
    """One card in the recommended play plan."""
    name: str
    role: str
    value: int
    energy_cost: int


@dataclass
class StrategySuggestion:
    """Full turn strategy computed from hand + incoming damage."""
    incoming_damage: int
    current_block: int
    block_needed: int

    suggested_cards: list[CardSuggestion]
    total_block_gain: int
    total_damage: int
    energy_used: int
    energy_remaining: int

    block_surplus: int
    damage_surplus: int
    is_safe: bool
    any_lethal: list[str]


def _effective_damage(card: Card, strength: int, vigor: int,
                      is_weak: bool, vuln_enemies: bool) -> int:
    """Quick damage estimate for sorting; doesn't consume vigor."""
    if not card.is_attack:
        return 0
    base = card.damage + strength + vigor
    if is_weak:
        base = math.floor(base * WEAK_DAMAGE_MULTIPLIER)
    if vuln_enemies:
        base = math.floor(base * VULNERABLE_MULTIPLIER)
    return max(base, 0) * max(card.hits, 1)


def compute_strategy(state: GameState) -> StrategySuggestion:
    """
    Solve: given incoming damage, pick cards in optimal order.

    Strategy:
    1. Play draw cards first (more options; especially good at full energy to dig for plays / Sly).
    2. If we have Sly cards in hand, play discard effects early so Sly triggers (card plays when discarded).
    3. Play Weak/Vulnerable debuffs before attacks.
    4. Play block cards to cover incoming damage.
    4. Play poison cards (add to damage).
    5. Play AOE attacks.
    6. Play single-target attacks.

    Considers: draw, Weak/Vulnerable/Frail, Poison, AOE, energy gain; defensive buffs
    (Intangible, Plating, Buffer, Thorns); setup (Block/Draw/Energy next turn, Retain, Strength, Dexterity, Vigor).
    """
    incoming = calculate_incoming_damage(state)
    energy = state.player.energy
    dex = state.player.dexterity
    strength = state.player.strength
    vigor = state.player.vigor
    is_weak = state.player.weak_turns > 0
    num_enemies = len(state.enemies)

    any_vuln = any(e.is_vulnerable for e in state.enemies)

    block_needed = max(incoming.total_incoming - state.player.block, 0)

    block_cards: list[tuple[int, Card, int]] = []
    attack_cards: list[tuple[int, Card, int]] = []
    draw_cards: list[tuple[int, Card, int]] = []
    debuff_cards: list[tuple[int, Card, str, int]] = []
    poison_cards: list[tuple[int, Card, int]] = []
    aoe_cards: list[tuple[int, Card, int]] = []
    defensive_buff_cards: list[tuple[int, Card, int]] = []
    setup_cards: list[tuple[int, Card, int]] = []
    discard_cards: list[tuple[int, Card, int]] = []
    hand_has_sly = False

    for i, card in enumerate(state.hand):
        eff = parse_card_effects(card.name, card.card_type, card.description)

        if eff.draw > 0:
            draw_cards.append((i, card, eff.draw))
        if eff.has_sly:
            hand_has_sly = True
        if eff.causes_discard > 0:
            discard_cards.append((i, card, eff.causes_discard))
        if eff.applies_weak > 0:
            debuff_cards.append((i, card, "weak", eff.applies_weak))
        if eff.applies_vulnerable > 0:
            debuff_cards.append((i, card, "vulnerable", eff.applies_vulnerable))
        if eff.applies_poison > 0 and not (card.is_attack or (eff.is_aoe and eff.aoe_damage > 0)):
            poison_cards.append((i, card, eff.applies_poison))
        if eff.is_aoe and eff.aoe_damage > 0:
            fake = Card(card.name, eff.aoe_damage, card.energy_cost, card.card_type)
            aoe_dmg = _effective_damage(fake, strength, vigor, is_weak, any_vuln)
            aoe_cards.append((i, card, aoe_dmg))
        if card.is_attack and not (eff.is_aoe and eff.aoe_damage > 0):
            dmg = _effective_damage(card, strength, vigor, is_weak, any_vuln)
            attack_cards.append((i, card, dmg))
        if card.block > 0:
            blk = compute_card_block(card, dex, is_frail=state.player.frail_turns > 0)
            block_cards.append((i, card, blk))
        if (
            card.block <= 0
            and not card.is_attack
            and eff.draw <= 0
            and eff.applies_weak <= 0
            and eff.applies_vulnerable <= 0
            and not (eff.is_aoe and eff.aoe_damage > 0)
            and (eff.applies_poison <= 0 or (eff.applies_poison > 0 and (card.is_attack or (eff.is_aoe and eff.aoe_damage > 0))))
        ):
            if eff.grants_intangible or eff.grants_plating or eff.grants_buffer or eff.grants_thorns:
                val = eff.grants_intangible + eff.grants_plating + eff.grants_buffer + eff.grants_thorns
                defensive_buff_cards.append((i, card, val))
            if (
                eff.grants_block_next_turn
                or eff.grants_draw_next_turn
                or eff.grants_energy_next_turn
                or eff.grants_retain_hand
                or eff.grants_strength
                or eff.grants_dexterity
                or eff.grants_vigor
            ):
                val = (
                    eff.grants_block_next_turn
                    + eff.grants_draw_next_turn
                    + eff.grants_energy_next_turn
                    + (1 if eff.grants_retain_hand else 0)
                    + eff.grants_strength
                    + eff.grants_dexterity
                    + eff.grants_vigor
                )
                setup_cards.append((i, card, val))

    def _eff_sort(t: tuple) -> float:
        return t[2] / max(t[1].energy_cost, MIN_ENERGY_FOR_SORT)

    block_cards.sort(key=_eff_sort, reverse=True)
    attack_cards.sort(key=_eff_sort, reverse=True)
    draw_cards.sort(key=lambda t: t[2], reverse=True)
    poison_cards.sort(key=lambda t: t[2], reverse=True)
    aoe_cards.sort(key=_eff_sort, reverse=True)
    defensive_buff_cards.sort(key=_eff_sort, reverse=True)
    setup_cards.sort(key=_eff_sort, reverse=True)
    discard_cards.sort(key=lambda t: (t[2], -t[1].energy_cost), reverse=True)

    suggested: list[CardSuggestion] = []
    used_indices: set[int] = set()
    total_block_gain = 0
    total_single_dmg = 0
    total_aoe_dmg = 0
    total_poison = 0
    energy_left = energy

    weak_applied = False
    vuln_applied = False

    def _play_card(idx: int, card: Card, role: str, value: int):
        nonlocal energy_left, total_block_gain, total_single_dmg, total_aoe_dmg, total_poison
        if card.energy_cost > energy_left:
            return False
        suggested.append(CardSuggestion(
            name=card.name, role=role, value=value, energy_cost=card.energy_cost,
        ))
        used_indices.add(idx)
        energy_left -= card.energy_cost
        eff = parse_card_effects(card.name, card.card_type, card.description)
        if eff.gains_energy > 0:
            energy_left += eff.gains_energy
        return True

    for idx, card, draw_val in draw_cards:
        if idx in used_indices:
            continue
        _play_card(idx, card, "draw", draw_val)

    if hand_has_sly:
        for idx, card, discard_val in discard_cards:
            if idx in used_indices:
                continue
            if card.energy_cost <= energy_left:
                _play_card(idx, card, "discard_sly", discard_val)

    for idx, card, debuff_type, _ in debuff_cards:
        if idx in used_indices:
            continue
        if debuff_type == "vulnerable":
            vuln_applied = True
        elif debuff_type == "weak":
            weak_applied = True
        _play_card(idx, card, "debuff", 1)

    if vuln_applied:
        any_vuln = True
    if weak_applied and block_needed > 0:
        block_needed = max(0, int(block_needed * WEAK_BLOCK_REDUCTION))

    remaining_deficit = block_needed
    for idx, card, blk in block_cards:
        if idx in used_indices:
            continue
        if card.energy_cost > energy_left:
            continue
        if _play_card(idx, card, "block", blk):
            total_block_gain += blk
            remaining_deficit -= blk
            if remaining_deficit <= 0:
                break

    for idx, card, val in defensive_buff_cards:
        if idx in used_indices:
            continue
        if block_needed > 0 and card.energy_cost <= energy_left:
            _play_card(idx, card, "defensive_buff", val)

    for idx, card, poison_val in poison_cards:
        if idx in used_indices:
            continue
        if _play_card(idx, card, "poison", poison_val):
            total_poison += poison_val * num_enemies

    for idx, card, aoe_val in aoe_cards:
        if idx in used_indices:
            continue
        if _play_card(idx, card, "aoe", aoe_val * num_enemies):
            total_aoe_dmg += aoe_val * num_enemies
            eff = parse_card_effects(card.name, card.card_type, card.description)
            if eff.applies_poison > 0:
                total_poison += eff.applies_poison * num_enemies

    for idx, card, dmg in attack_cards:
        if idx in used_indices:
            continue
        if _play_card(idx, card, "attack", dmg):
            total_single_dmg += dmg
            eff = parse_card_effects(card.name, card.card_type, card.description)
            if eff.applies_poison > 0:
                total_poison += eff.applies_poison * num_enemies

    for idx, card, val in setup_cards:
        if idx in used_indices:
            continue
        if card.energy_cost <= energy_left:
            _play_card(idx, card, "setup", val)

    total_dmg = total_single_dmg + total_aoe_dmg
    total_effective_block = state.player.block + total_block_gain
    block_surplus = total_effective_block - incoming.total_incoming
    is_safe = block_surplus >= 0

    total_aoe_per_enemy = total_aoe_dmg // num_enemies if num_enemies else 0
    poison_per_enemy = total_poison // num_enemies if num_enemies else 0

    any_lethal: list[str] = []
    for enemy in state.enemies:
        effective_hp = enemy.hp + enemy.block
        aoe_to_them = total_aoe_per_enemy
        poison_to_them = poison_per_enemy + enemy.poison
        single_needed = max(0, effective_hp - aoe_to_them - poison_to_them)
        if single_needed <= total_single_dmg or effective_hp <= aoe_to_them + poison_to_them:
            any_lethal.append(enemy.name)

    return StrategySuggestion(
        incoming_damage=incoming.total_incoming,
        current_block=state.player.block,
        block_needed=block_needed,
        suggested_cards=suggested,
        total_block_gain=total_block_gain,
        total_damage=total_dmg,
        energy_used=energy - energy_left,
        energy_remaining=energy_left,
        block_surplus=block_surplus,
        damage_surplus=0,
        is_safe=is_safe,
        any_lethal=any_lethal,
    )


# ── Hand summary (quick stats, no strategy) ──────────────────────────

@dataclass
class HandSummary:
    """Quick stats about what the hand contains."""
    attack_count: int = 0
    block_count: int = 0
    other_count: int = 0
    total_potential_damage: int = 0
    total_potential_block: int = 0
    total_attack_energy: int = 0
    total_block_energy: int = 0
    max_playable_damage: int = 0
    max_playable_block: int = 0


def summarize_hand(state: GameState) -> HandSummary:
    """Calculate quick hand stats with energy constraints."""
    s = HandSummary()
    dex = state.player.dexterity
    strength = state.player.strength
    vigor = state.player.vigor
    is_weak = state.player.weak_turns > 0
    any_vuln = any(e.is_vulnerable for e in state.enemies)

    playable_attacks: list[tuple[int, int]] = []
    playable_blocks: list[tuple[int, int]] = []

    for card in state.hand:
        if card.is_attack:
            s.attack_count += 1
            dmg = _effective_damage(card, strength, vigor, is_weak, any_vuln)
            s.total_potential_damage += dmg
            s.total_attack_energy += card.energy_cost
            playable_attacks.append((dmg, card.energy_cost))
        elif card.block > 0:
            s.block_count += 1
            blk = compute_card_block(card, dex, is_frail=state.player.frail_turns > 0)
            s.total_potential_block += blk
            s.total_block_energy += card.energy_cost
            playable_blocks.append((blk, card.energy_cost))
        else:
            s.other_count += 1

    playable_attacks.sort(key=lambda t: t[0] / max(t[1], MIN_ENERGY_FOR_SORT), reverse=True)
    energy = state.player.energy
    for dmg, cost in playable_attacks:
        if cost <= energy:
            s.max_playable_damage += dmg
            energy -= cost

    playable_blocks.sort(key=lambda t: t[0] / max(t[1], MIN_ENERGY_FOR_SORT), reverse=True)
    energy = state.player.energy
    for blk, cost in playable_blocks:
        if cost <= energy:
            s.max_playable_block += blk
            energy -= cost

    return s


# ── Legacy helpers (kept for test compatibility) ──────────────────────

def _apply_relic_combat_start(state: GameState) -> tuple[int, int]:
    bonus_vigor = 0
    bonus_vulnerable_all = 0
    for relic in state.relics:
        if relic.effect_type == "combat_start":
            bonus_vigor += relic.grants_vigor
            bonus_vulnerable_all += relic.applies_vulnerable_all
    return bonus_vigor, bonus_vulnerable_all


def calculate_turn_damage(
    state: GameState,
    target_enemy_index: int = 0,
    card_play_order: Sequence[int] | None = None,
) -> TurnResult:
    if target_enemy_index >= len(state.enemies):
        return TurnResult(enemy_name="(none)", enemy_hp=0)

    enemy = state.enemies[target_enemy_index]
    relic_vigor, relic_vuln_all = _apply_relic_combat_start(state)
    enemy_vulnerable = enemy.is_vulnerable or (relic_vuln_all > 0 and state.turn == 1)

    energy = state.player.energy
    strength = state.player.strength
    is_weak = state.player.weak_turns > 0
    vigor = state.player.vigor
    first_attack_vigor = relic_vigor if state.turn == 1 else 0

    if card_play_order is None:
        card_play_order = list(range(len(state.hand)))

    results: list[DamageResult] = []
    total_damage = 0
    total_block = 0
    attack_count = 0

    for idx in card_play_order:
        if idx >= len(state.hand):
            continue
        card = state.hand[idx]
        if card.energy_cost > energy:
            continue

        energy -= card.energy_cost

        if card.is_attack:
            base = card.damage + strength
            active_vigor = vigor + (first_attack_vigor if attack_count == 0 else 0)
            per_hit = base + active_vigor
            if is_weak:
                per_hit = math.floor(per_hit * WEAK_DAMAGE_MULTIPLIER)
            if enemy_vulnerable:
                per_hit = math.floor(per_hit * VULNERABLE_MULTIPLIER)
            per_hit = max(per_hit, 0)
            total = per_hit * max(card.hits, 1)

            dr = DamageResult(
                card_name=card.name, raw_damage=card.damage,
                final_damage=per_hit, hits=card.hits,
                total_damage=total, energy_spent=card.energy_cost,
            )
            results.append(dr)
            total_damage += total
            attack_count += 1
            vigor = 0
        else:
            total_block += card.block + state.player.dexterity

    return TurnResult(
        enemy_name=enemy.name,
        enemy_hp=enemy.hp,
        per_card=results,
        total_damage=total_damage,
        total_block=total_block,
        energy_remaining=energy,
        is_lethal=total_damage >= enemy.hp,
        overkill=max(total_damage - enemy.hp, 0),
    )


def calculate_all_enemies(state: GameState) -> list[TurnResult]:
    return [calculate_turn_damage(state, i) for i in range(len(state.enemies))]
