from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Sequence

from .card_effects import parse_card_effects
from .models import Card, Enemy, GameState, PlayerState, Relic


VULNERABLE_MULTIPLIER = 1.5
WEAK_DAMAGE_MULTIPLIER = 0.75
MIN_ENERGY_FOR_SORT = 0.5


# ── Low-level card math ────────────────────────────────────────────────

@dataclass
class DamageResult:
    """Result of a single card being played against a single enemy."""
    card_name: str
    raw_damage: int
    final_damage: int
    hits: int
    total_damage: int
    energy_spent: int


@dataclass
class TurnResult:
    """Aggregated result for the whole turn against a target enemy."""
    enemy_name: str
    enemy_hp: int
    per_card: list[DamageResult] = field(default_factory=list)
    total_damage: int = 0
    total_block: int = 0
    energy_remaining: int = 0
    is_lethal: bool = False
    overkill: int = 0


def compute_card_damage(
    card: Card,
    strength: int,
    vigor: int,
    is_weak: bool,
    enemy_vulnerable: bool,
) -> int:
    """Return total damage one card deals (all hits) to one enemy."""
    if not card.is_attack:
        return 0

    base = card.damage + strength
    per_hit = base + vigor

    if is_weak:
        per_hit = math.floor(per_hit * WEAK_DAMAGE_MULTIPLIER)
    if enemy_vulnerable:
        per_hit = math.floor(per_hit * VULNERABLE_MULTIPLIER)

    return max(per_hit, 0) * max(card.hits, 1)


FRAIL_BLOCK_MULTIPLIER = 0.75


def compute_card_block(card: Card, dexterity: int, is_frail: bool = False) -> int:
    """Return block generated by one skill card. Frail reduces block by 25%."""
    if card.is_attack or card.block <= 0:
        return 0
    blk = card.block + dexterity
    if is_frail:
        blk = math.floor(blk * FRAIL_BLOCK_MULTIPLIER)
    return blk


# ── Incoming damage ───────────────────────────────────────────────────

@dataclass
class EnemyIncoming:
    name: str
    intended_damage: int
    intended_hits: int
    total_damage: int
    move_type: str


@dataclass
class IncomingDamageResult:
    """Breakdown of incoming enemy damage for the turn."""
    per_enemy: list[EnemyIncoming] = field(default_factory=list)
    total_incoming: int = 0
    player_block: int = 0
    net_damage: int = 0
    expected_hp: int = 0


def calculate_incoming_damage(state: GameState) -> IncomingDamageResult:
    """Calculate total damage enemies will deal and net HP loss after current block."""
    per_enemy: list[EnemyIncoming] = []
    total_incoming = 0

    for enemy in state.enemies:
        dmg = enemy.intended_damage
        per_enemy.append(EnemyIncoming(
            name=enemy.name,
            intended_damage=enemy.intended_damage,
            intended_hits=enemy.intended_hits,
            total_damage=dmg,
            move_type=enemy.intended_move,
        ))
        total_incoming += dmg

    player_block = state.player.block
    net_damage = max(total_incoming - player_block, 0)
    expected_hp = max(state.player.hp - net_damage, 0)

    return IncomingDamageResult(
        per_enemy=per_enemy,
        total_incoming=total_incoming,
        player_block=player_block,
        net_damage=net_damage,
        expected_hp=expected_hp,
    )


def _effective_damage(card: Card, strength: int, vigor: int,
                      is_weak: bool, vuln_enemies: bool) -> int:
    """Quick damage estimate for sorting; doesn't consume vigor."""
    if not card.is_attack:
        return 0
    base = card.damage + strength + vigor
    if is_weak:
        base = math.floor(base * WEAK_DAMAGE_MULTIPLIER)
    if vuln_enemies:
        base = math.floor(base * VULNERABLE_MULTIPLIER)
    return max(base, 0) * max(card.hits, 1)



# ── Hand summary (quick stats, no strategy) ──────────────────────────

@dataclass
class HandSummary:
    """Quick stats about what the hand contains."""
    attack_count: int = 0
    block_count: int = 0
    other_count: int = 0
    total_potential_damage: int = 0
    total_potential_block: int = 0
    total_attack_energy: int = 0
    total_block_energy: int = 0
    max_playable_damage: int = 0
    max_playable_block: int = 0


def summarize_hand(state: GameState) -> HandSummary:
    """Calculate quick hand stats with energy constraints."""
    s = HandSummary()
    dex = state.player.dexterity
    strength = state.player.strength
    vigor = state.player.vigor
    is_weak = state.player.weak_turns > 0
    any_vuln = any(e.is_vulnerable for e in state.enemies)

    playable_attacks: list[tuple[int, int]] = []
    playable_blocks: list[tuple[int, int]] = []

    for card in state.hand:
        if card.is_attack:
            s.attack_count += 1
            dmg = _effective_damage(card, strength, vigor, is_weak, any_vuln)
            s.total_potential_damage += dmg
            s.total_attack_energy += card.energy_cost
            playable_attacks.append((dmg, card.energy_cost))
        elif card.block > 0:
            s.block_count += 1
            blk = compute_card_block(card, dex, is_frail=state.player.frail_turns > 0)
            s.total_potential_block += blk
            s.total_block_energy += card.energy_cost
            playable_blocks.append((blk, card.energy_cost))
        else:
            s.other_count += 1

    playable_attacks.sort(key=lambda t: t[0] / max(t[1], MIN_ENERGY_FOR_SORT), reverse=True)
    energy = state.player.energy
    for dmg, cost in playable_attacks:
        if cost <= energy:
            s.max_playable_damage += dmg
            energy -= cost

    playable_blocks.sort(key=lambda t: t[0] / max(t[1], MIN_ENERGY_FOR_SORT), reverse=True)
    energy = state.player.energy
    for blk, cost in playable_blocks:
        if cost <= energy:
            s.max_playable_block += blk
            energy -= cost

    return s


# ── Legacy helpers (kept for test compatibility) ──────────────────────

def _apply_relic_combat_start(state: GameState) -> tuple[int, int]:
    bonus_vigor = 0
    bonus_vulnerable_all = 0
    for relic in state.relics:
        if relic.effect_type == "combat_start":
            bonus_vigor += relic.grants_vigor
            bonus_vulnerable_all += relic.applies_vulnerable_all
    return bonus_vigor, bonus_vulnerable_all


def calculate_turn_damage(
    state: GameState,
    target_enemy_index: int = 0,
    card_play_order: Sequence[int] | None = None,
) -> TurnResult:
    if target_enemy_index >= len(state.enemies):
        return TurnResult(enemy_name="(none)", enemy_hp=0)

    enemy = state.enemies[target_enemy_index]
    relic_vigor, relic_vuln_all = _apply_relic_combat_start(state)
    enemy_vulnerable = enemy.is_vulnerable or (relic_vuln_all > 0 and state.turn == 1)

    energy = state.player.energy
    strength = state.player.strength
    is_weak = state.player.weak_turns > 0
    vigor = state.player.vigor
    first_attack_vigor = relic_vigor if state.turn == 1 else 0

    if card_play_order is None:
        card_play_order = list(range(len(state.hand)))

    results: list[DamageResult] = []
    total_damage = 0
    total_block = 0
    attack_count = 0

    for idx in card_play_order:
        if idx >= len(state.hand):
            continue
        card = state.hand[idx]
        if card.energy_cost > energy:
            continue

        energy -= card.energy_cost

        if card.is_attack:
            base = card.damage + strength
            active_vigor = vigor + (first_attack_vigor if attack_count == 0 else 0)
            per_hit = base + active_vigor
            if is_weak:
                per_hit = math.floor(per_hit * WEAK_DAMAGE_MULTIPLIER)
            if enemy_vulnerable:
                per_hit = math.floor(per_hit * VULNERABLE_MULTIPLIER)
            per_hit = max(per_hit, 0)
            total = per_hit * max(card.hits, 1)

            dr = DamageResult(
                card_name=card.name, raw_damage=card.damage,
                final_damage=per_hit, hits=card.hits,
                total_damage=total, energy_spent=card.energy_cost,
            )
            results.append(dr)
            total_damage += total
            attack_count += 1
            vigor = 0
        else:
            total_block += card.block + state.player.dexterity

    return TurnResult(
        enemy_name=enemy.name,
        enemy_hp=enemy.hp,
        per_card=results,
        total_damage=total_damage,
        total_block=total_block,
        energy_remaining=energy,
        is_lethal=total_damage >= enemy.hp,
        overkill=max(total_damage - enemy.hp, 0),
    )


def calculate_all_enemies(state: GameState) -> list[TurnResult]:
    return [calculate_turn_damage(state, i) for i in range(len(state.enemies))]
